### ISSUE TITLE
FIXME: Vercel doesn't want to build solenoid

### ISSUE THREAD

**Issue by stationaryStation** [Revolt-Unofficial-Clients/Solenoid#53]
From the logs:

```log
Error: Module format cjs does not support top-level await. Use the "es" or "system" output formats rather.
at error (file:///vercel/path0/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
at Chunk.render (file:///vercel/path0/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:14878:20)
 at file:///vercel/path0/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:15812:52
at Array.map (<anonymous>)
at Bundle.addFinalizedChunksToBundle (file:///vercel/path0/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:15810:34)
 at Bundle.generate (file:///vercel/path0/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:15790:24)
 at async file:///vercel/path0/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:23795:27
 at async catchUnfinishedHookActions (file:///vercel/path0/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:23126:20)
at async Object.build (file:///vercel/path0/node_modules/.pnpm/solid-start-vercel@0.2.7_pwel2bd237mbr7ooh5pghdxziu/node_modules/solid-start-vercel/index.js:57:7) {
code: 'INVALID_TLA_FORMAT',
  id: '/vercel/path0/.solid/server/entry-server.js'
}
```

Can someone please help me fix this build error?

**Comment by ericwaetke** [comment]
Hey, I've got the same error. Do you remember what you did to fix it?
